# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdcaf4f7000a3731e346af9c7a495bb640194107c737bffae4ca0b66a6668532f96931964caa82fb0aeba9d153dea27ac3a270d6a18400125094dcce5dca7be8

test:
  secret_key_base: 555117001f086350b116277be1cc558d5a51ad685c351222fc88f3c2869bb7574040b4fa3a6c690c597d7972b2cd0051c3f49ef52307f8d92222f44d51cd0c0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
